import type { Product } from "@shared/schema";

import blackHoodie from "@assets/generated_images/black_premium_dev_hoodie.png";
import whiteTshirt from "@assets/generated_images/white_minimal_dev_tshirt.png";
import navySweatshirt from "@assets/generated_images/navy_blue_dev_sweatshirt.png";
import grayTshirt from "@assets/generated_images/gray_database_tshirt.png";
import greenHoodie from "@assets/generated_images/green_medical_hoodie.png";
import burgundyShirt from "@assets/generated_images/burgundy_engineer_shirt.png";

export const products: Product[] = [
  {
    id: "committed-hoodie",
    name: "Committed",
    tagline: "// git commit -m \"to you forever\"",
    description: "For those who commit to their code and their relationships. Premium cotton blend hoodie that's as reliable as your version control. Because real developers know that the best commits are the ones you never revert.",
    price: 599,
    originalPrice: undefined,
    category: "developer",
    type: "hoodie",
    colors: ["black", "charcoal", "navy"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [blackHoodie],
    featured: true,
    new: true,
    inStock: true,
  },
  {
    id: "404-not-found-tee",
    name: "404: Sleep Not Found",
    tagline: "// Error: REM_CYCLE_UNDEFINED",
    description: "The official uniform for debugging at 3 AM. When your sleep pattern returns null and your coffee dependency is critical. Made from ultra-soft cotton that feels like the cloud services you can't afford.",
    price: 599,
    category: "developer",
    type: "t-shirt",
    colors: ["white", "black", "charcoal"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    images: [whiteTshirt],
    featured: true,
    new: false,
    inStock: true,
  },
  {
    id: "merge-conflict-crew",
    name: "Merge Conflict",
    tagline: "// HEAD -> main | relationship -> complicated",
    description: "When your code conflicts but your style doesn't. This premium crewneck celebrates the beautiful chaos of collaborative development. Soft, comfortable, and unlike your git history, always clean.",
    price: 599,
    originalPrice: undefined,
    category: "developer",
    type: "sweatshirt",
    colors: ["navy", "charcoal", "black"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [navySweatshirt],
    featured: true,
    new: false,
    inStock: true,
  },
  {
    id: "query-everything-tee",
    name: "Query Everything",
    tagline: "// SELECT * FROM life WHERE meaning IS NOT NULL",
    description: "For database enthusiasts who question everything. This shirt runs faster than your unindexed queries. Premium fabric that won't normalize your style but will definitely structure your look.",
    price: 599,
    category: "developer",
    type: "t-shirt",
    colors: ["charcoal", "white", "black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [grayTshirt],
    featured: false,
    new: true,
    inStock: true,
  },
  {
    id: "on-call-hoodie-med",
    name: "On Call",
    tagline: "// status: ALWAYS_AVAILABLE",
    description: "For medical professionals who never truly clock out. Comfortable enough for 24-hour shifts, stylish enough for rounds. The pager may be gone, but the commitment remains. Premium heavyweight cotton for those cold hospital nights.",
    price: 599,
    category: "medical",
    type: "hoodie",
    colors: ["forest", "navy", "black"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [greenHoodie],
    featured: true,
    new: true,
    inStock: true,
  },
  {
    id: "stat-order-tee",
    name: "STAT Order",
    tagline: "// priority: CRITICAL | eta: NOW",
    description: "When everything is urgent but you still have style. For healthcare heroes who run toward emergencies in comfort. Premium quick-dry fabric because you're already running.",
    price: 599,
    category: "medical",
    type: "t-shirt",
    colors: ["white", "forest", "navy"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    images: [whiteTshirt],
    featured: false,
    new: false,
    inStock: true,
  },
  {
    id: "over-engineered-longsleeve",
    name: "Over Engineered",
    tagline: "// complexity: O(n!) | style: O(1)",
    description: "For engineers who always find the most elegant solution, eventually. This long-sleeve is structurally sound and aesthetically optimized. Premium construction that could survive a peer review.",
    price: 599,
    category: "engineering",
    type: "long-sleeve",
    colors: ["burgundy", "charcoal", "navy"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [burgundyShirt],
    featured: true,
    new: false,
    inStock: true,
  },
  {
    id: "under-pressure-tee",
    name: "Under Pressure",
    tagline: "// psi: HIGH | composure: HIGHER",
    description: "When deadlines compress but your style expands. For engineers who thrive under stress and always deliver. Premium fabric that handles pressure better than most project managers.",
    price: 599,
    category: "engineering",
    type: "t-shirt",
    colors: ["black", "charcoal", "white"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [grayTshirt],
    featured: false,
    new: true,
    inStock: true,
  },
  {
    id: "pixel-perfect-hoodie",
    name: "Pixel Perfect",
    tagline: "// margin: 0 | padding: immaculate",
    description: "For designers who obsess over every detail. When your mockups are flawless and your hoodie should be too. Premium cotton that's as smooth as your gradients and as consistent as your design system.",
    price: 599,
    category: "designer",
    type: "hoodie",
    colors: ["black", "white", "charcoal"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [blackHoodie],
    featured: false,
    new: true,
    inStock: true,
  },
  {
    id: "undefined-behavior-tee",
    name: "Undefined Behavior",
    tagline: "// result: ¯\\_(ツ)_/¯",
    description: "For those moments when the code works but nobody knows why. Embrace the chaos with this premium tee. Soft cotton that's more predictable than your legacy codebase.",
    price: 599,
    category: "developer",
    type: "t-shirt",
    colors: ["black", "charcoal", "navy"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    images: [blackHoodie],
    featured: false,
    new: false,
    inStock: true,
  },
  {
    id: "coffee-dependency-crew",
    name: "Coffee Dependency",
    tagline: "// import { sanity } from 'caffeine'",
    description: "Required for all builds. This crewneck understands that coffee isn't a want, it's a core dependency. Premium warmth for those long compilation times.",
    price: 599,
    category: "developer",
    type: "sweatshirt",
    colors: ["charcoal", "black", "navy"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [navySweatshirt],
    featured: false,
    new: false,
    inStock: true,
  },
  {
    id: "first-do-no-harm-tee",
    name: "First, Do No Harm",
    tagline: "// except to disease | error_handling: aggressive",
    description: "The original code of conduct. For medical professionals who took an oath and take it seriously. Premium comfort for those who comfort others.",
    price: 599,
    category: "medical",
    type: "t-shirt",
    colors: ["white", "navy", "forest"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    images: [whiteTshirt],
    featured: false,
    new: false,
    inStock: true,
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "all") return products;
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function getNewProducts(): Product[] {
  return products.filter((p) => p.new);
}
